[package]
name = "event"
description = "Typed hooks, async coordination, and redraw signaling for Mitos"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foldhash.workspace = true
hashbrown.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time", "sync", "parking_lot", "macros"] }
# the event registry is essentially read only but must be an rwlock so we can
# setup new events on initialization, hardware-lock-elision hugely benefits this case
# as it essentially makes the lock entirely free as long as there is no writes 
parking_lot = { workspace = true, features = ["hardware-lock-elision", "send_guard"] }
anyhow.workspace = true
log.workspace = true
futures-executor.workspace = true

[features]
integration_test = []
