[workspace]
resolver = "2"
members = [
  "mitos-core",
  "mitos-view",
  "mitos-term",
  "mitos-tui",
  "mitos-lsp-types",
  "mitos-lsp",
  "mitos-event",
  "mitos-dap-types",
  "mitos-dap",
  "mitos-loader",
  "mitos-vcs",
  "mitos-parsec",
  "mitos-stdx",
  "xtask",
]

default-members = [
  "mitos-term"
]

[profile.release]
lto = "thin"

[profile.opt]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
opt-level = 3

[profile.integration]
inherits = "test"
package.mitos-core.opt-level = 2
package.mitos-tui.opt-level = 2
package.mitos-term.opt-level = 2

[workspace.dependencies]
tree-house = { version = "0.4", default-features = false }
nucleo = "0.5.0"
slotmap = "1.1.1"
thiserror = "2.0"
tempfile = "3.27.0"
bitflags = "2.12"
unicode-segmentation = "1.13"
ropey = { version = "1.6.1", default-features = false, features = ["simd"] }
foldhash = "0.2"
parking_lot = "0.12"
futures-executor = "0.3"
futures-util = { version = "0.3", features = ["std", "async-await"], default-features = false }
tokio-stream = "0.1.18"
toml = "1.1"
termina = "0.3"
sonic-rs = "0.5"
globset = "0.4"
etcetera = "0.11"
arc-swap = "1.9"
arrayvec = "0.7"
ratatui = { version = "0.30.2", default-features = false, features = ["layout-cache", "std", "underline-color"] }

# dev dependencies
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
quickcheck = { version = "1", default-features = false }

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
categories = ["editor"]
repository = "https://github.com/matoous/mitos"
homepage = "https://github.com/matoous/mitos"
license = "MPL-2.0"
rust-version = "1.90"
