# Gruvbox Material for Helix
# Original Author: @sainnhe (https://github.com/sainnhe/gruvbox-material)
# Ported by: @satoqz
# License: MIT (see licenses/gruvbox_material.license)

inherits = "gruvbox_material_dark_medium"
