[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mitos-term = { path = "../mitos-term" }
mitos-core = { path = "../mitos-core" }
mitos-view = { path = "../mitos-view" }
mitos-loader = { path = "../mitos-loader" }
mitos-stdx = { path = "../mitos-stdx" }
ropey.workspace = true
toml.workspace = true
