[package]
name = "loader"
description = "Build bootstrapping for Mitos crates"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "loader"
path = "src/main.rs"

[dependencies]
stdx.workspace = true

anyhow.workspace = true
serde.workspace = true
toml.workspace = true
etcetera.workspace = true
parking_lot.workspace = true
sha2.workspace = true
globset.workspace = true
log.workspace = true

# TODO: these two should be on !wasm32 only

# cloning/compiling tree-sitter grammars
cc.workspace = true
threadpool.workspace = true
tempfile.workspace = true

tree-house.workspace = true
