[package]
name = "parsec"
description = "Small parser combinators for Mitos command and snippet parsers"
include = ["src/**/*", "README.md", "LICENSE"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
