[package]
name = "command-line"
description = "Command-line tokenization and argument parsing for Mitos"
include = ["src/**/*", "README.md", "LICENSE"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
