[package]
name = "stdx"
description = "Focused standard-library extensions shared across Mitos"
include = ["src/**/*", "README.md", "LICENSE"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
dunce.workspace = true
etcetera.workspace = true
ropey.workspace = true
which.workspace = true
regex-cursor.workspace = true
bitflags.workspace = true
regex-automata.workspace = true
unicode-segmentation.workspace = true
serde.workspace = true
percent-encoding.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Threading"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs", "thread"] }

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
